# Generated by Django 4.2.25 on 2025-11-09 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("content", models.TextField()),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="Short description of the post",
                        max_length=500,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100)),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="List of tags"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="published",
                        max_length=20,
                    ),
                ),
                ("published", models.BooleanField(default=True)),
                (
                    "coverImage",
                    models.ImageField(
                        blank=True,
                        help_text="Cover image for the post",
                        null=True,
                        upload_to="posts/covers/",
                    ),
                ),
                (
                    "readingTime",
                    models.IntegerField(
                        default=0, help_text="Estimated reading time in minutes"
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "ordering": ["-createdAt"],
                "indexes": [
                    models.Index(
                        fields=["-createdAt"], name="posts_post_created_453541_idx"
                    ),
                    models.Index(fields=["slug"], name="posts_post_slug_59b922_idx"),
                    models.Index(
                        fields=["status", "published"],
                        name="posts_post_status_0335ac_idx",
                    ),
                ],
            },
        ),
    ]
