# Generated by Django 4.2.25 on 2025-11-09 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Follow",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "followerName",
                    models.CharField(
                        blank=True,
                        help_text="Cached name of the follower",
                        max_length=200,
                    ),
                ),
                (
                    "followerPhotoURL",
                    models.URLField(
                        blank=True,
                        help_text="Cached photo URL of the follower",
                        max_length=500,
                    ),
                ),
                (
                    "followingName",
                    models.CharField(
                        blank=True,
                        help_text="Cached name of the user being followed",
                        max_length=200,
                    ),
                ),
                (
                    "followingPhotoURL",
                    models.URLField(
                        blank=True,
                        help_text="Cached photo URL of the user being followed",
                        max_length=500,
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "followerId",
                    models.ForeignKey(
                        db_column="followerId",
                        help_text="User who is following",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "followingId",
                    models.ForeignKey(
                        db_column="followingId",
                        help_text="User being followed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Follow",
                "verbose_name_plural": "Follows",
                "ordering": ["-createdAt"],
                "indexes": [
                    models.Index(
                        fields=["-createdAt"], name="follows_fol_created_7768ac_idx"
                    ),
                    models.Index(
                        fields=["followerId", "-createdAt"],
                        name="follows_fol_followe_62673c_idx",
                    ),
                    models.Index(
                        fields=["followingId", "-createdAt"],
                        name="follows_fol_followi_4be5f5_idx",
                    ),
                ],
                "unique_together": {("followerId", "followingId")},
            },
        ),
    ]
