# Generated by Django 4.2.25 on 2025-11-09 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="View",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "isGuest",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this view is from a guest user",
                    ),
                ),
                ("viewedAt", models.DateTimeField(auto_now_add=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "postId",
                    models.ForeignKey(
                        db_column="postId",
                        help_text="The post that was viewed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="posts.post",
                    ),
                ),
                (
                    "userId",
                    models.ForeignKey(
                        blank=True,
                        db_column="userId",
                        help_text="User who viewed the post. Null for guest views.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="post_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "View",
                "verbose_name_plural": "Views",
                "ordering": ["-viewedAt"],
                "indexes": [
                    models.Index(
                        fields=["-viewedAt"], name="views_view_viewedA_36a143_idx"
                    ),
                    models.Index(
                        fields=["postId", "-viewedAt"],
                        name="views_view_postId_ad8083_idx",
                    ),
                    models.Index(
                        fields=["userId", "-viewedAt"],
                        name="views_view_userId_8cf2c4_idx",
                    ),
                ],
            },
        ),
    ]
