# Generated by Django 4.2.25 on 2025-11-09 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("text", models.TextField(help_text="Comment text content")),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "postId",
                    models.ForeignKey(
                        db_column="postId",
                        help_text="The post this comment belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="posts.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the comment. Null for anonymous comments.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
                "ordering": ["-createdAt"],
                "indexes": [
                    models.Index(
                        fields=["-createdAt"], name="comments_co_created_454300_idx"
                    ),
                    models.Index(
                        fields=["postId", "-createdAt"],
                        name="comments_co_postId_360b62_idx",
                    ),
                ],
            },
        ),
    ]
