# Generated by Django 4.2.25 on 2025-11-09 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Share",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("linkedin", "LinkedIn"),
                            ("whatsapp", "WhatsApp"),
                            ("telegram", "Telegram"),
                            ("reddit", "Reddit"),
                            ("email", "Email"),
                            ("copy_link", "Copy Link"),
                            ("other", "Other"),
                        ],
                        default="unknown",
                        help_text="Platform where the post was shared",
                        max_length=50,
                    ),
                ),
                (
                    "isGuest",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this share is from a guest user",
                    ),
                ),
                ("sharedAt", models.DateTimeField(auto_now_add=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "postId",
                    models.ForeignKey(
                        db_column="postId",
                        help_text="The post that was shared",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="posts.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who shared the post. Null for guest shares.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Share",
                "verbose_name_plural": "Shares",
                "ordering": ["-sharedAt"],
                "indexes": [
                    models.Index(
                        fields=["-sharedAt"], name="shares_shar_sharedA_96cbe1_idx"
                    ),
                    models.Index(
                        fields=["postId", "-sharedAt"],
                        name="shares_shar_postId_f1a5c2_idx",
                    ),
                    models.Index(
                        fields=["user", "-sharedAt"],
                        name="shares_shar_user_id_74ac05_idx",
                    ),
                    models.Index(
                        fields=["platform", "-sharedAt"],
                        name="shares_shar_platfor_cacce9_idx",
                    ),
                ],
            },
        ),
    ]
