# Generated by Django 4.2.25 on 2025-11-09 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address of the subscriber",
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("subscribedAt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Newsletter Subscription",
                "verbose_name_plural": "Newsletter Subscriptions",
                "ordering": ["-subscribedAt"],
                "indexes": [
                    models.Index(
                        fields=["-subscribedAt"], name="newsletters_subscri_d14da9_idx"
                    ),
                    models.Index(fields=["email"], name="newsletters_email_d3a4d3_idx"),
                ],
            },
        ),
    ]
