# Generated by Django 4.2.25 on 2025-11-09 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Like",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "isGuest",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this like is from a guest user",
                    ),
                ),
                ("likedAt", models.DateTimeField(auto_now_add=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                (
                    "postId",
                    models.ForeignKey(
                        db_column="postId",
                        help_text="The post that was liked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="posts.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who liked the post. Null for guest likes.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Like",
                "verbose_name_plural": "Likes",
                "ordering": ["-likedAt"],
                "indexes": [
                    models.Index(
                        fields=["-likedAt"], name="likes_like_likedAt_1b17dc_idx"
                    ),
                    models.Index(
                        fields=["postId", "-likedAt"],
                        name="likes_like_postId_95e856_idx",
                    ),
                    models.Index(
                        fields=["user", "-likedAt"],
                        name="likes_like_user_id_c9e180_idx",
                    ),
                ],
                "unique_together": {("postId", "user")},
            },
        ),
    ]
