# Generated by Django 4.2.25 on 2025-11-09 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the person contacting", max_length=200
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address for response",
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("message", models.TextField(help_text="Contact message content")),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "ordering": ["-createdAt"],
                "indexes": [
                    models.Index(
                        fields=["-createdAt"], name="contacts_co_created_390752_idx"
                    ),
                    models.Index(fields=["email"], name="contacts_co_email_25f973_idx"),
                ],
            },
        ),
    ]
